config/routes.rb
Chive::Engine.routes.draw do
  resources :articles, path: '/', param: :slug
end

app/models/chive/application_record.rb
module Chive
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/chive/article.rb
module Chive
  class Article < ApplicationRecord
    belongs_to :author, class_name: Chive.user_model, primary_key: Chive.user_pk_attr,
                        foreign_key: :author_id, required: false

    has_one_attached :image

    acts_as_taggable_on :tags

    validates :title, presence: true

    before_validation :set_slug
    validate :slug_is_parameter
    validates :slug, presence: true, uniqueness: true

    validate :valid_status

    before_save :maybe_summarize

    def byline
      return custom_byline if custom_byline.present?
      return real_author_name if real_author_name.present?
      Chive.anonymous_name
    end

    def real_author_name
      author.present? && author.send(Chive.user_name_attr)
    end

    def pending?
      published_at > DateTime.now
    end

    def expired?
      expired_at && expired_at <= DateTime.now
    end

    def published?
      self.status == 'publish'
    end

    def draft?
      self.status == 'draft'
    end

    def public?
      self.status == 'publish' && !pending? && !expired?
    end

    def to_param
      slug
    end

    def set_slug
      self.slug ||= Chive.slug_formatter.call(self)
    end

    def self.latest
      self.order(published_at: :desc, created_at: :desc)
    end

    def self.latest_published
      now = DateTime.now
      latest.where('published_at <= ? AND (expired_at >= ? OR expired_at IS NULL) AND status = ?', now, now, 'publish')
    end

    private

    def valid_status
      errors.add(:status, :invalid) unless ['publish', 'draft'].include?(status)
    end

    def slug_is_parameter
      errors.add(:slug, 'must be a valid parameter') unless slug.parameterize == slug
    end

    def maybe_summarize
      return unless autosummary
      self.summary = summarize_body
    end

    def summarize_body
      doc = Nokogiri::HTML.parse(body)
      paras = doc.css('p')
      return if paras.empty? || paras.one?
      paras.first.text
    end
  end
end

app/controllers/chive/application_controller.rb
require 'ostruct'

module Chive
  class ApplicationController < ActionController::Base
    include Chive::UserConcerns

    protect_from_forgery with: :exception

    after_action(:store_action) if Chive.use_devise?

    # Needed to fix polymorphic_mappings.
    # @see https://github.com/rails/rails/issues/31325#issuecomment-560135329
    before_action :import_main_app_polymorphic_mappings

    private

    # Needed to fix polymorphic_mappings.
    # @see https://github.com/rails/rails/issues/31325#issuecomment-560135329
    def import_main_app_polymorphic_mappings
      Chive::Engine.routes.polymorphic_mappings.merge! Rails.application.routes.polymorphic_mappings
    end

    def store_action
      return unless request.get?
      if (request.path != "/users/sign_in" &&
          request.path != "/users/sign_up" &&
          request.path != "/users/password/new" &&
          request.path != "/users/password/edit" &&
          request.path != "/users/confirmation" &&
          request.path != "/users/sign_out" &&
          !request.xhr?) # don't store ajax calls
        store_location_for(Chive.user_model.underscore.to_sym, request.fullpath)
      end
    end
  end
end

app/controllers/chive/articles_controller.rb
require_dependency "chive/application_controller"

module Chive
  class ArticlesController < ApplicationController
    layout Chive.public_layout, only: [:index, :show]

    before_action :authenticate_chive_user, except: [:index, :show]

    before_action :set_article, only: [:show, :edit, :update, :destroy]

    # GET /articles
    # GET /articles.json
    def index
      @articles = if user_can_chive? && !params.key?(:public)
        Article.latest
      else
        Article.latest_published
      end.paginate(page: params[:page], per_page: Chive.per_page)
    end

    # GET /articles/1
    # GET /articles/1.json
    def show
      raise ActionController::RoutingError.new('Not Found') unless @article
    end

    # GET /articles/new
    def new
      @article = Article.new(published_at: DateTime.now)
    end

    # GET /articles/1/edit
    def edit
    end

    # POST /articles
    # POST /articles.json
    def create
      @article = Article.new(article_params)
      @article.author = chive_user

      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, notice: 'Article was successfully created.' }
          format.json { render :show, status: :created, location: @article }
        else
          format.html { render :new }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /articles/1
    # PATCH/PUT /articles/1.json
    def update
      respond_to do |format|
        if params[:delete_image] || params[:article][:image]
          @article.image.purge
        end
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /articles/1
    # DELETE /articles/1.json
    def destroy
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find_by(slug: params[:slug])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params[:article].permit(:title, :slug, :body, :custom_byline, :autosummary, :summary, :published_at, :expired_at, :status, :tag_list, :image)
    end
  end
end

app/controllers/chive/feed_controller.rb
module Chive
  class FeedController < ApplicationController
    def index
      @articles =  Article.latest_published.limit(Chive.per_page)
      respond_to do |format|
        format.rss { render layout: false }
      end
    end
  end
end

app/controllers/concerns/chive/user_concerns.rb
module Chive
  module UserConcerns
    extend ActiveSupport::Concern

    included do
      helper_method :user_can_chive?
      helper_method :chive_user
    end

    def authenticate_chive_user
      if Chive.use_devise?
        send("authenticate_#{Chive.user_model.underscore}!")
      elsif Rails.env.development?
          flash[:alert] = "Warning: Authentication is not implemented. Access to admin pages is enabled in development only."
      else
        # @todo super or raise or something?
        raise "Authentication is not implemented"
      end
    end

    def chive_user
      send("current_#{Chive.user_model.underscore}") if Chive.use_devise?
    end

    def user_can_chive?
      if Chive.use_devise?
        user_signed_in?
      else
        Rails.env.development?
      end
    end
  end
end

app/helpers/chive/application_helper.rb
module Chive
  module ApplicationHelper
    # Needed to fix polymorphic_mappings.
    # @see https://github.com/rails/rails/issues/31325#issuecomment-560135329
    def method_missing(method, *args, &block)
      if method.to_s.end_with?("_path", "_url")
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    # Needed to fix polymorphic_mappings.
    # @see https://github.com/rails/rails/issues/31325#issuecomment-560135329
    def respond_to?(method)
      if method.to_s.end_with?("_path", "_url")
        if main_app.respond_to?(method)
          true
        else
          super
        end
      else
        super
      end
    end
  end
end

app/views/chive/articles/_delete_modal.erb
<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        Are you sure you want to delete this article?
      </div>
      <div class="modal-footer">
        <%= link_to 'Delete', @article, method: :delete, class: 'btn btn-danger' %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
      </div>
    </div>
  </div>
</div>

app/views/chive/articles/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<%= form_for @article, html: { multipart: true } do |f| %>
  <div class="row">
    <nav class="col text-right">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', @article, class: 'btn btn-secondary' %>
      <% if params[:action] == 'edit' %>
        <%= link_to "Delete", '#', class: 'btn btn-outline-danger', data: { toggle: 'modal', target: '#delete-modal' } %>
        <%= render partial: 'delete_modal' %>
      <% end %>
    </nav>
  </div>
  <div class="row">
    <div class="col">
      <h1><%= params[:action].capitalize %> Article</h1>
    </div>
  </div>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> errors prohibited this article from being saved:</h2>
      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :slug %>
    <%= f.text_field :slug, class: 'form-control input-slug', disabled: true %>
    <label>
      <%= hidden_field_tag :curr_slug, @article.slug %>
      <%= check_box_tag :edit_slug_checkbox %>
      Edit Slug
    </label>
  </div>
  <div class="row">
    <div class="col-md-9">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.cktext_area :body, class: 'form-control', ckeditor: { height: 512 } %>
      </div>
    </div>
    <div class="col-md-3">
      <div class="form-group image-upload-fields">
        <%= f.label :image %>
        <div class="image-previews">
          <div class="image-container">
            <img src="/assets/chive/no-image.png" class="align-middle" />
          </div>
          <div>
            <% if @article.image.attached? %>
              <div class="image-container">
                <%= image_tag @article.image.variant(resize: '250x250'), class: 'attached-image' if @article.image.attached? %>
              </div>
              <label class="delete-image btn">
                <%= check_box_tag :delete_image, @article.image.id, false %>
              </label>
            <% end %>
          </div>
          <div>
            <div class="image-container">
              <img src="/assets/chive/blank.png" class="image-preview" />
            </div>
            <label class="delete-preview btn">
              <%= check_box_tag :delete_preview, 'delete', false %>
            </label>
          </div>
        </div>
        <div class="input-group">
          <div class="custom-file">
            <%= f.file_field :image, class: 'image-upload custom-file-input', data: {preview: '.image-preview', delete: '.delete-preview' } %>
            <%= f.label :image, 'Choose file', class: 'custom-file-label' %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :tag_list, 'Tags' %><br>
        <%= f.text_field :tag_list, value: @article.tag_list.to_s, class: 'form-control' %>
      </div>
      <div class="form-group">
        <div class="form-group">
          <%= f.label :summary %><br>
          <div class="checkbox">
            <label>
              <%= f.check_box :autosummary, class: 'checkbox' %>
              Use automatic summary
            </label>
          </div>
          <%= f.text_area :summary, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :custom_byline, 'Byline' %>
        <%= f.text_field :custom_byline, class: 'form-control', placeholder: @article.author ? @article.author.name : chive_user ? chive_user.name : 'Anonymous' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :status %>
      <%= f.select :status, [['Publish', :publish], ['Draft', :draft]], {}, {class: 'form-control'} %>
    </div>
    <div class="form-group col-sm-4">
      <%= f.label :published_at, 'Publish Date' %>
      <%= f.text_field :published_at, class: 'form-control flatpickr-datetime' %>
    </div>
    <div class="form-group col-sm-4">
      <%= f.label :exipred_at, 'Expire Date' %>
      <%= f.text_field :expired_at, class: 'form-control flatpickr-datetime' %>
    </div>
  </div>
<% end %>

app/views/chive/articles/_pagination.html.erb
<div class="row mb-4">
  <div class="col"></div>
  <div class="flickr_pagination col-auto">
    <%= will_paginate @articles %>
  </div>
  <div class="col"></div>
</div>

app/views/chive/articles/_status.html.erb
<% if user_can_chive? %>
  <p>
    <% if article.draft? %><span class="badge badge-info">Draft</span><% end %>
    <% if article.expired? %><span class="badge badge-info">Expired</span><% end %>
    <% unless article.public? %>
      <% if chive_user %>
        <span class="badge badge-info">Visible to authors</span>
      <% elsif Rails.env.development? %>
        <span class="badge badge-info">Visible in development</span>
      <% end %>
    <% end %>
    <% if !article.draft? && !article.public? %>
      <span class="badge badge-danger">Status: <%= article.status %></span>
    <% end %>
  </p>
<% end %>

app/views/chive/articles/edit.html.erb
<%= render partial: 'form' %>

app/views/chive/articles/index.html.erb
<section>
  <% if user_can_chive? %>
    <div class="row">
      <nav class="col text-right">
        <%= link_to "New Article", new_article_path, class: 'btn btn-outline-primary' %>
      </nav>
    </div>
  <% end %>

  <%= render 'pagination' %>

  <% @articles.each do |article| %>
    <div class="row mb-4">
    </div>
    <article>
      <h2 class="large"><%= link_to article.title, article_path(article) %></h2>
      <address>by <%= article.byline %> on <%= article.published_at %></address>
      <p>
    		<%= raw article.summary %>
	    </p>
      <%= render 'status', article: article %>
    </article>
  <% end %>
  
  <%= render 'pagination' %>
</section>

app/views/chive/articles/new.html.erb
<%= render partial: 'form' %>

app/views/chive/articles/show.html.erb
<% if user_can_chive? %>
  <div class="row mb-4">
    <nav class="col text-right">
      <%= link_to "Edit", edit_article_path(@article), class: 'btn btn-outline-primary' %>
      <%= render partial: 'delete_modal' %>
    </nav>
  </div>
<% end %>

<section>
  <article>
    <div class="row">
      <% if @article.image.attached? %>
        <div class="col-auto">
          <%= image_tag @article.image.variant(resize: '400x300') %>
        </div>
      <% end %>
      <div class="col-md">
        <h1><%= @article.title %></h1>
        <address>by <%= @article.byline %> on <%= @article.published_at %></address>
        <p>
          <small><%= @article.tag_list.to_s %></small>
        </p>
        <%= render 'status', article: @article %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= raw @article.body %>
      </div>
    </div>
  </article>
</section>

<nav>
  <%= link_to 'More Articles', articles_path %>
</nav>

app/views/layouts/chive/_flash.html.erb
<% unless flash.empty? %>
    <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
        <% flash.each do |type, msg| %>
            <div class="container <%= type %>">
                <%= msg %>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <% end %>
    </div>
<% end %>

app/views/layouts/chive/_userbox.html.erb
<% if Chive.use_devise? %>
  <% if chive_user %>
    <div>
      <span>Signed in as <%= chive_user.send(Chive.user_name_attr.underscore) %></span>
    </div>
    <div>
      <%= link_to 'Sign Out', send("destroy_#{Chive.user_model.underscore}_session_path"), method: :delete, class: 'header-link align-middle' %>
    </div>
  <% else %>
    <%= link_to 'Sign In', send("new_#{Chive.user_model.underscore}_session_path"), class: 'header-link' %>
  <% end %>
<% elsif Rails.env.development? %>
  <div>
    <span class="badge badge-warning">DEV MODE: NO AUTHENTICATION</span>
  </div>
<% end %>

app/views/layouts/chive/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chive</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= javascript_include_tag "chive/application" %>
  <%= stylesheet_link_tag    "chive/application", media: "all" %>
</head>
  <body>
    <header id="header">
      <div class="container">
        <div class="row justify-content-between">
          <div class="col">
            <h1 class="header-title"><%= link_to 'Articles', articles_path, class: 'header-link align-middle' %></h1>
          </div>
          <nav class="col text-right">
            <%= render "layouts/chive/userbox" %>
          </nav>
        </div>
      </div>
    </header>
    <%= render partial: 'layouts/chive/flash' %>

    <main id="main" class="container">
      <%= yield %>
    </main>

    <footer class="container text-center mb-4">
      <p>
        <small>Powered by Chive</small>
      </p>
    </footer>
  </body>
</html>